CC = cgdb

all: debug


debug: 
	$(CC) ./bomb

# this shell will split the debug console into left and right
# echo -e "set ignorecase\nset ts=4\nset wso=vertical\nset eld=shortarrow\nset hls\n" > ~/.cgdb/cgdbrc